"""add catalog tables

Revision ID: 99e68c15ff30
Revises: 
Create Date: 2026-07-24 11:00:19.752409

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99e68c15ff30'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('synopsis', sa.String(length=5000), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('rating_score', sa.Float(), nullable=True),
    sa.Column('rating_votes', sa.Integer(), nullable=True),
    sa.Column('rating_source', sa.String(length=64), nullable=True),
    sa.Column('genre_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('studio_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('producer_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('tag_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animes_country_code'), 'animes', ['country_code'], unique=False)
    op.create_index(op.f('ix_animes_slug'), 'animes', ['slug'], unique=True)
    op.create_index(op.f('ix_animes_status'), 'animes', ['status'], unique=False)
    op.create_index(op.f('ix_animes_type'), 'animes', ['type'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_table('producers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producers_slug'), 'producers', ['slug'], unique=True)
    op.create_table('studios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studios_slug'), 'studios', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anime_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'number', name='uq_season_anime_number')
    )
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('synopsis', sa.String(length=5000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'number', name='uq_episode_season_number')
    )
    op.create_table('streaming_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('external_ref', sa.String(length=500), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('audio_language_code', sa.String(length=2), nullable=False),
    sa.Column('audio_language_name', sa.String(length=255), nullable=False),
    sa.Column('subtitle_language_code', sa.String(length=2), nullable=True),
    sa.Column('subtitle_language_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'provider_name', 'external_ref', name='uq_streaming_source_episode_provider_ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streaming_sources')
    op.drop_table('episodes')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_studios_slug'), table_name='studios')
    op.drop_table('studios')
    op.drop_index(op.f('ix_producers_slug'), table_name='producers')
    op.drop_table('producers')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_animes_type'), table_name='animes')
    op.drop_index(op.f('ix_animes_status'), table_name='animes')
    op.drop_index(op.f('ix_animes_slug'), table_name='animes')
    op.drop_index(op.f('ix_animes_country_code'), table_name='animes')
    op.drop_table('animes')
    # ### end Alembic commands ###
